version: "3.9"

networks:
  poshtaNet:
    driver: bridge

services:
  postgresServerDb:
    image: postgres:18.1
    container_name: postgres_db
    restart: always
    ports:
      - "3674:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${VOLUME_POSTGRES}
    networks:
      - poshtaNet

  api:
    image: utereskovi/poshtaNet-django:latest
    container_name: poshtaNet_api
    volumes:
      - /data/poshtaNet/images:/app/images
    environment:
      DEBUG: "False"
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DB_HOST: postgresServerDb
      DB_PORT: 5432
    ports:
      - "5898:8000"   # Django usually runs on 8000
    depends_on:
      - postgresServerDb
    networks:
      - poshtaNet
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn config.wsgi:application --bind 0.0.0.0:8000"

  front:
    image: utereskovi/poshtaNet-react:latest
    container_name: poshtaNet_front
    ports:
      - "2488:80"